version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/flyway/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306

  testing-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/flyway/sql:/docker-entrypoint-initdb.d
    ports:
      - ${TESTING_DB_PORT}:3306

#        flyway-migrate:
#          image: flyway/flyway:6.0.1
#          volumes:
#            - ./docker/flyway/sql:/flyway/sql
#            - ./docker/flyway/conf/flyway.conf:/flyway/conf/flyway.conf
#          depends_on:
#            - mysql
#          command: migrate

#  testing-flyway-migrate:
#    image: flyway/flyway:6.0.1
#    volumes:
#      - ./docker/flyway/sql:/flyway/sql
#      - ./docker/flyway/conf/testing_flyway.conf:/flyway/conf/flyway.conf
#    depends_on:
#      - testing-mysql
#    command: migrate
